language: go

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - libasound2-dev
            - libpulse-dev
            - libwebkitgtk-3.0-dev
      script:
        - ./dist/release-linux.sh
    - os: osx
      osx_image: xcode8.3
      script:
        - ./dist/release-macos.sh

install:
  - git fetch --unshallow --tags

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file_glob: true
  file: "dist/glitch-*.tar.gz"
  skip_cleanup: true
  on:
    tags: true
