language: go

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - libasound2-dev
    - os: osx

script:
  - go get ./...
  - go generate ./...
  - go test ./...
  - go build -o glitch ./cmd/glitch

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file_glob: true
  file: glitch
  skip_cleanup: true
  on:
    tags: true

